spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/echo_db
    username: echo
    password: echo#2025
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: oussamachahidi20@gmail.com
    password: ypix apew uddv ekbb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
